### ISSUE TITLE
App Link in Moonbase Wallet Opens Incorrectly from Discord

### ISSUE THREAD

**Issue by reasje** [MXCzkEVM/moonchain-wallet#78]
When selecting the Invitation link from the Discord app, the link redirects but does not open the intended page

redirection link https://mxc1usd.com/app/openDapp?url=https://app.blueberryring.com?invite=p8M6E7b02M

[Refrenced issue.](https://github.com/MXCzkEVM/doitring/issues/86)

**Comment by reasje** [comment]
Also pasting link in the browsers is not working both Android & IOS.

**Comment by reasje** [comment]
This is a expected behavior : [check here](https://github.com/react-navigation/react-navigation/issues/2525)
![Image](https://github.com/user-attachments/assets/58776563-96a5-4304-9325-68d317c1d82f)
[Link to topic](https://stackoverflow.com/questions/37069816/deep-linking-not-working-in-chrome)

**Comment by reasje** [comment]
Dev log: 
There might be an [approach](https://www.reddit.com/r/Telegram/comments/dci0nf/how_do_i_make_it_so_that_links_open_directly_in/) to handle this but It wouldn't be good option.

**Comment by reasje** [comment]
@SanghamitraBhowmick1993 I just pushed the fix, Just use the same link you should be fimliar the way It works. Now the link should work from Telegeam Discord browsers etc

**Comment by SanghamitraBhowmick1993** [comment]
looks great now! on iOS clicking the link from discord now takes me to the dapps dashboard
