### ISSUE TITLE
Dapps UI Issue

### ISSUE THREAD

**Issue by reasje** [MXCzkEVM/moonchain-wallet#85]
Phone model Oppo N3 
![Image](https://github.com/user-attachments/assets/7b2ba784-1699-4999-b9f7-ca7449ea4b98)

**Comment by reasje** [comment]
Dev log:
According to [this](https://www.gsmarena.com/oppo_find_n3-12205.php) website the Resolution for this device are 2268 * 2240.

**Comment by sheenhx** [comment]
![Image](https://github.com/user-attachments/assets/67be9a12-a249-4134-b43a-d5f4661ed204)
